# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/RESEARCH/Downloads/Quadrature/Quadrature/FPGA_part/source/servo_enc.xdc

# IP: ip/ila_0_1/ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet
